placement_portal/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.registerView, name = 'register'),
    path('login/', views.loginView, name = 'login'),
    path('', views.homeView, name = 'home'),
    path('logout/', views.logoutView, name = 'logout'),
    path('notices/', views.noticeView, name = 'notices'),
    path('apply/<str:jobId>/', views.applyToJobView, name = 'apply'),
    path('applications/', views.applicantView, name = 'applications'),
    path('about/', views.aboutView, name="about")
]

placement_portal/customAdmin/urls.py
from django.urls import path
from . import views

app_name = 'customAdmin'

urlpatterns = [
    path('jobs/',views.adminJobView,name = 'jobs'),
    path('view/applications/<str:jobId>',views.adminJobApplicationsView,name = 'applications'),
    path('download/<str:jobId>',views.adminDownloadCsvFile,name = 'download'),
    path('applications/change-status',views.adminChangeApplicationView,name = 'changeStatus')
]

placement_portal/placement_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace = 'accounts')),
    path('custom-admin/',include('customAdmin.urls',namespace = 'customadmin'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.site_header = 'Placement Portal Administration'
admin.site.index_title = 'Welcome to Placement-Portal'
admin.site.site_title = 'Placement-Portal'

placement_portal/customAdmin/models.py
from django.db import models
# Create your models here.

placement_portal/customAdmin/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.models import noticeModel, jobModel
from accounts.models import applicantModel
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import csv
from django.http import FileResponse
import json
import os
# Create your views here.

@login_required(login_url = 'accounts:login')
def adminJobView(request):
    jobList = jobModel.objects.filter().order_by('-lastDateToApply')
    jobPaginator = Paginator(jobList, 6)

    page = request.GET.get('page')
    page_obj = jobPaginator.get_page(page)
    context = {'page_obj': page_obj}
    return render(request, 'customAdmin/jobs.html', context)

@login_required(login_url = 'accounts:login')
def adminJobApplicationsView(request, jobId):
    applicationsList = applicantModel.objects.filter(jobId=jobId)
    applicationsPaginator = Paginator(applicationsList, 6)
    page = request.GET.get('page')
    page_obj = applicationsPaginator.get_page(page)
    job = jobModel.objects.filter(pk=jobId)
    context = {'page_obj': page_obj, 'job': job[0]}
    return render(request, 'customAdmin/applications.html', context)

def adminDownloadCsvFile(request,jobId):
    applicationsList = applicantModel.objects.filter(jobId = jobId)
    filename = 'applicants_list_jobId-{0}.csv'.format(jobId)
    fields = ['Registration_Id','First_Name','Last_Name','Job_Id','Job_Name','Status']
    f = 0
    with open(filename,'w', newline="") as csvfile:
        csvwriter = csv.writer(csvfile)
        if f == 0:
            csvwriter.writerow(fields)
            f = 1
        for application in applicationsList:
            row = [application.user.username,application.user.first_name,application.user.last_name,application.jobId.id,application.jobId.name,application.status]
            csvwriter.writerow(row)
    f = open(filename, 'rb')
    response = FileResponse(f)
    return response

def adminChangeApplicationView(request):
    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)
    JobId = body['jobId']
    Status = body['status']
    ID = body['appId']
    applicant = applicantModel.objects.get(id = ID)
    if not applicant:
        print("No application found")
    else :
       applicant.status = Status
       applicant.save()
    response = HttpResponse("")
    response.status_code = 200
    return response

placement_portal/customAdmin/templates/customAdmin/applications.html
{% extends 'accounts/base.html' %}
{%block title%}Applications{%endblock title%}
{% block styles %}
<style>
</style>
{% endblock styles%}
{% block content %}
<div>
    <div class="border-bottom mx-1 d-flex justify-content-between align-items-center">
        <div class="display-4 ">Applications</div>
        <div><a href="{% url 'customadmin:download' job.id %}" class="btn btn-dark" target="blank">Download list</a></div>
    </div>
    <div class="mt-2">
        <p><span class="text-warning">Job Name: </span>{{ job.name }}</p>
        <p><span class="text-warning">Salary ( In Rupees ): </span>{{ job.salary }}</p>
        <p><span class="text-warning">Company Name:</span> {{ job.cName.name }}</p>
        <p><span class="text-warning">Company Address:</span> {{ job.cName.address }}</p>
        <p><span class="text-warning">Last date to apply:</span>
            {{job.lastDateToApply.day}}/{{job.lastDateToApply.month}}/{{job.lastDateToApply.year}}</p>
        
    </div>
    <div class="table-responsive">
        <table class="table table-sm table-bordered table-light mt-1">
            <thead class="thead-dark">
                <tr>
                    <th>Application Id</th>
                    <th>Registration Id</th>
                    <th>Name</th>
                    <th>Application status</th>
                </tr>
            </thead>
            <tbody>
                {% for app in page_obj %}
                <tr>
                    <td>{{ app.id }}</td>
                    <td>{{ app.user}}</td>
                    <td>{{ app.user.first_name }}&nbsp;{{ app.user.last_name }}</td>
                    <td>
                        <div class="btn-group btn-group-sm d-inline-flex justify-content-around">
                            <button type="button" onclick="changeStatus(event)" id="ip-{{app.id}}"
                                data-id="{{ app.id }}" data-success="btn-info" data-action="In Process" class="btn {% ifequal app.status 'In Process' %} btn-info {% else %} btn-dark
                        {% endifequal %}">In Process</button>
                            <button type="button" onclick="changeStatus(event)" id="h-{{app.id}}" data-id="{{ app.id }}"
                                data-success="btn-success" data-action="Hired" class="btn {% ifequal app.status 'Hired' %} btn-success {% else %} btn-dark
                        {% endifequal %}">Hired</button>
                            <button type="button" onclick="changeStatus(event)" id="r-{{app.id}}" data-id="{{ app.id }}"
                                data-success="btn-danger" data-action="Rejected" class="btn {% ifequal app.status 'Rejected' %} btn-danger {% else %} btn-dark
                        {% endifequal %}">Rejected</button>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-center m-2">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item border border-dark"><a class="page-link"
                    href="?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}

            {% if page_obj.has_next %}
            <li class="page-item border border-dark"><a class="page-link"
                    href="?page={{ page_obj.next_page_number }}">next</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<script>
    async function changeStatus(event) {
        function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        const response = await fetch("/custom-admin/applications/change-status", { method:"post",  mode: 'same-origin',headers: { 'Content-Type': "application/json",'X-CSRFToken': csrftoken}, body: JSON.stringify({ jobId: "{{ job.id }}", appId: `${event.target.dataset.id}`, status: `${event.target.dataset.action}` }) });
        if (response.status === 200) {
            const allButtons = document.querySelectorAll(`[data-id='${event.target.dataset.id}']`);
            for (let i = 0; i < allButtons.length; i++) {
                if (allButtons[i].id != event.target.id) {
                    allButtons[i].classList.remove(allButtons[i].dataset.success);
                    allButtons[i].classList.add("btn-dark");
                }
            }
            event.target.classList.add(event.target.dataset.success);
            event.target.classList.remove("btn-dark");
        }
        else {
            document.getElementById("message-box").innerHTML += `<div class="alert alert-dismissible alert-primary">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<a href="#" class="alert-link"> [Error code: ${response.status}] Application Status change failed</a>
	</div>`
        }
    }
</script>
{% endblock content %}

placement_portal/customAdmin/templates/customAdmin/jobs.html
{% extends 'accounts/base.html' %}
{%block title%}Jobs{%endblock title%}
{% block content %}
<div>
  <div class="display-4 border-bottom mx-1">
    Jobs
  </div>
  <table class="table table-hover mt-5" style="border: 1px solid black;">
  <thead>
    <tr class="table-primary">
      <th scope="col" style="font-size: 20px; border: 1px solid black;">Company Name</th>
      <th scope="col" style="font-size: 20px; border: 1px solid black;">Job Name</th>
      <th scope="col" style="font-size: 20px; border: 1px solid black;">Last Date</th>
      <th scope="col" style="font-size: 20px; border: 1px solid black;">Applications</th>
    </tr>
  </thead>
  <tbody>
  {% for app in page_obj %}
    <tr class="table-default">
      <th scope="row" style="font-size: 15px; border: 1px solid black;">{{ app.cName }}</th>
      <td style="font-size: 15px; border: 1px solid black;">{{ app.name }}</td>
      <td style="font-size: 15px; border: 1px solid black;">{{ app.lastDateToApply }}</td>
      <td style="font-size: 15px; border: 1px solid black;"><a class="btn btn-primary m-2" href="{% url 'customadmin:applications' app.id %}" >View Applications</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
<div class="d-flex justify-content-center m-2">
  <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item border border-dark"><a class="page-link"
              href="{% url 'customadmin:jobs' %}?page={{ page_obj.previous_page_number }}">previous</a></li>
      {% endif %}

      {% if page_obj.has_next %}
      <li class="page-item border border-dark"><a class="page-link"
              href="{% url 'customadmin:jobs' %}?page={{ page_obj.next_page_number }}">next</a></li>
      {% endif %}
  </ul>
</div>
</div>
{% endblock content %}