placement_portal/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.registerView, name = 'register'),
    path('login/', views.loginView, name = 'login'),
    path('', views.homeView, name = 'home'),
    path('logout/', views.logoutView, name = 'logout'),
    path('notices/', views.noticeView, name = 'notices'),
    path('apply/<str:jobId>/', views.applyToJobView, name = 'apply'),
    path('applications/', views.applicantView, name = 'applications'),
    path('about/', views.aboutView, name="about")
]

placement_portal/placement_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace = 'accounts')),
    path('custom-admin/',include('customAdmin.urls',namespace = 'customadmin'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.site_header = 'Placement Portal Administration'
admin.site.index_title = 'Welcome to Placement-Portal'
admin.site.site_title = 'Placement-Portal'

placement_portal/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
# Create your models here.
#company model

class companyModel(models.Model):

  #cId = models.IntegerField(primary_key = True,auto_created = True)
  name = models.CharField(max_length = 100, blank = False, unique = True)
  address = models.CharField(max_length = 100, blank = False)
  contact = models.CharField(max_length = 12,blank = False, unique = True)
  about = models.CharField(max_length = 50, blank = True)

  def __str__(self):
	  return self.name
# def path_to_upload_jd(instance,filename):
#   return 'JD/jd_{0}'.format(instance.cName)
#job model

class jobModel(models.Model):

  #jobId = models.IntegerField(primary_key = True,unique = True,auto_created = True)
  name = models.CharField(max_length = 30,blank = False,null = True)
  cName = models.ForeignKey(companyModel,on_delete= models.CASCADE, null = True)
  salary = models.CharField(max_length = 20,blank = True)
  dateOfArrival = models.DateField()
  lastDateToApply = models.DateField()
  jdFile = models.FileField(upload_to = 'FILES/JD/')
  
  def __str__(self):
	  return self.name

#applicant model
class applicantModel(models.Model):

  statusChoices = (
    ('Hired','Hired'),
    ('Rejected','Rejected'),
    ('In Process','In Process')
  )

  user = models.ForeignKey(User, on_delete = models.CASCADE)
  jobId = models.ForeignKey(jobModel, on_delete = models.CASCADE)
  status = models.CharField(max_length = 10,choices = statusChoices)


#notice/updates model

class noticeModel(models.Model):

  name = models.CharField(max_length = 20,blank = False,null = False,default = 'New Notice')
  noticeFile = models.FileField(upload_to = 'FILES/NOTICE/')
  subject = models.CharField(max_length = 100,blank = False)
  date = models.DateField(default = date.today)

  def __str__(self):
    return self.name

placement_portal/accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']
        #fields = '__all__'
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

placement_portal/accounts/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from .models import noticeModel, jobModel
from .models import applicantModel
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from datetime import date
from .mailEngine import sendRegistrationMail,sendApplyMail
from .forms import CreateUserForm
from django.contrib.auth.models import User

#from .models import *
# Create your views here.

def aboutView(request):
    return render(request, 'accounts/about.html', {})
    
def registerView(request):
    if request.user.is_authenticated and request.user.is_superuser:
        redirect('customadmin:jobs')
    elif request.user.is_authenticated and not (request.user.is_superuser):
        return redirect('accounts:home')
    else:
        registerForm = CreateUserForm()
        if request.method == 'POST':
            registerForm = CreateUserForm(request.POST)
            if registerForm.is_valid():
                registerForm.save()
                user1 = registerForm.cleaned_data.get('username')
                mail = registerForm.cleaned_data.get('email')
                first_name = registerForm.cleaned_data.get('first_name')
                last_name = registerForm.cleaned_data.get('last_name')
                messages.success(
                    request, 'Account was successfully created for ' + user1)
                subject, htmplTemplateName, to = 'welcome', 'registerMailTemplate.html', mail
                sendRegistrationMail(request,subject,htmplTemplateName,to,first_name,last_name)
                return redirect('accounts:login')
    context = {'registerForm': registerForm}
    return render(request, 'accounts/register.html', context)


def loginView(request):
    if request.user.is_authenticated and request.user.is_superuser:
        redirect('customadmin:customAdminJob')
    elif request.user.is_authenticated and not (request.user.is_superuser):
        return redirect('accounts:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if user.is_superuser:
                    return redirect('customadmin:jobs')
                else:
                    return redirect('accounts:home')
            else:
                messages.info(request, 'Inavlid Credentials..')
        context = {}
        return render(request, 'accounts/login.html', context)


@login_required(login_url='accounts:login')
def homeView(request):
    if request.user.is_superuser:
        return redirect('customadmin:jobs')
    jobs = jobModel.objects.filter().order_by('-lastDateToApply')
    jobPaginator = Paginator(jobs, 6)
    page_number = request.GET.get('page')
    page_obj = jobPaginator.get_page(page_number)
    context = {'jobs': jobs, 'page_obj': page_obj}
    return render(request, 'accounts/dashboard.html', context)


def logoutView(request):
    logout(request)
    return redirect('accounts:login')


@login_required(login_url='accounts:login')
def noticeView(request):
    notices = noticeModel.objects.filter().order_by('-date')
    noticePaginator = Paginator(notices, 6)
    page_number = request.GET.get('page')
    page_obj = noticePaginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'accounts/notices.html', context)


@login_required(login_url='accounts:login')
def applicantView(request):
    applications = applicantModel.objects.filter(user=request.user)
    appsPaginator = Paginator(applications, 6)
    page_number = request.GET.get('page')
    page_obj = appsPaginator.get_page(page_number)
    context = {'page_obj': page_obj, 'noapplications': False}
    if not applications:
        context['noapplications'] = True
    return render(request, 'accounts/applications.html', context)


@login_required(login_url='accounts:login')
def applyToJobView(request, jobId):
    condition1 = Q(user=request.user)
    condition2 = Q(jobId=jobId)
    checkIfDatePassed = jobModel.objects.get(id = jobId)
    userObj = User.objects.get(username = request.user)
    checkIfApplied = applicantModel.objects.filter(condition1 & condition2)
    if len(checkIfApplied):
        messages.info(request, 'Already applied...')
    elif date.today()>checkIfDatePassed.lastDateToApply:
        messages.success(request, 'Cannot apply date passed..')
    else:
        applicant = applicantModel(
            user=request.user, jobId=jobModel(id=jobId), status='In Process')
        applicant.save()
        sendApplyMail(request,"Job Application","applyMailTemplate.html",userObj.email,checkIfDatePassed.name,checkIfDatePassed.cName)
        messages.success(request, 'Applied successfully...')

    return redirect('accounts:home')

placement_portal/accounts/templates/accounts/about.html
{% extends 'accounts/base.html' %}

{% block title %}About{% endblock title %}
{% block styles%}
<style>
    .about-card {
        border: solid 2px gray;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        margin: auto;
        /* max-width: 90%; */
    }

    .background-yellow {
        background-color: rgb(255, 183, 0);
    }

    .about-main {
        font-size: 1.5rem;
        border-bottom: solid 3px rgb(197, 197, 197);
    }

    .about-page {
        max-width: 70%;
        margin: 2rem auto;
        padding: 2rem;
        border: solid 2px brown;
    }

    .about-title,
    .about-title:hover {
        color: brown;
        font-family: 'Lekton', sans-serif;
        font-size: 3rem;
        text-decoration: underline;
        cursor: default;
    }

    .about-title:hover {
        text-decoration-color: rgb(0, 0, 0);
    }

    .about-name {
        font-size: 1.5rem;
    }

    .about-link {
        font-size: 1.2rem;
        font-family: 'Lekton', sans-serif;
        font-weight: bold;
        color: rgb(211, 127, 0);
        font-style: italic;
    }

    .about-link:hover {
        color:brown;
    }
</style>
{% endblock styles%}

{% block content %}
<div class="about-page background-yellow text-center">
    <div class="about-card text-center bg-light">
        <div>
            <div class="about-title">About</div>
            <div class="about-main">Placements is a placement portal where candidates get notifications regarding jobs
                and internships</div>
        </div>
        <div class="about-main">
            <div class="about-title">Contributors</div>
            <div class="about-name">
                Shreyas Kulkarni&nbsp;<a class="about-link" href="https://github.com/shreyas710" target="blank"><span>&#123;%</span><span>&nbsp;shreyas710&nbsp;</span><span>%&#125;</span></a>
            </div>
            <div class="about-name">
                Sojas Khandagale&nbsp;<a class="about-link" href="https://github.com/sojas07" target="blank"><span>&#123;%</span><span>&nbsp;sojas07&nbsp;</span><span>%&#125;</span></a>
            </div>
            <div class="about-name">
                Sanket Varpe&nbsp;<a class="about-link" href="https://github.com/sanketvarpe" target="blank"><span>&#123;%</span><span>&nbsp;sanketvarpe&nbsp;</span><span>%&#125;</span></a>

            </div>
            <div class="about-name">
                Sanket Wadekar&nbsp;<a class="about-link" href="https://github.com/sanketwadekar" target="blank"><span>&#123;%</span><span>&nbsp;sanketwadekar&nbsp;</span><span>%&#125;</span></a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

placement_portal/accounts/templates/accounts/applications.html
{% extends 'accounts/base.html' %}
{%block title%}Applications{%endblock title%}
{% block content %}
<div>
  <div class="display-4 border-bottom mx-2">
    Applications
  </div>
  {% if noapplications %}<h4 class="text-center">
    No applications !!! <a class="text-info" href="{% url 'accounts:home' %}">Apply now</a>
  </h4>
  {% else %}
    <div class="container" style="padding-left: 10px; padding-right: 10px; margin-top:50px;">
      <ul class="responsive-table">
        <li class="table-header" style="border-radius: 3px; 
                                          padding: 25px 30px; 
                                          display: flex; 
                                          justify-content: space-between; 
                                          margin-bottom: 25px; background-color: #95A5A6; 
                                          font-size: 20px; 
                                          text-transform: uppercase; 
                                          letter-spacing: 0.03em; border: 1px solid black;">
          <div class="col col-1" style="flex-basis: 10%;">Company Name</div>
          <div class="col col-2" style="flex-basis: 40%;">Job Name</div>
          <div class="col col-3" style="flex-basis: 25%;">Salary</div>
          <div class="col col-4" style="flex-basis: 25%;">Status</div>
        </li>
          {% for app in page_obj %}
            <li class="table-row" style="border-radius: 3px;
                                          padding: 25px 30px;
                                          display: flex;
                                          justify-content: space-between;
                                          margin-bottom: 25px; background-color: #ffffff;
                                          box-shadow: 0px 0px 9px 0px rgba(0,0,0,0.1);
                                          font-size: 15px;
                                          border: 1px solid black;">
              <div class="col col-1" style="flex-basis: 10%;">{{ app.jobId.cName.name }}</div>
              <div class="col col-2" style="flex-basis: 40%;">{{ app.jobId }}</div>
              <div class="col col-3" style="flex-basis: 25%;">{{ app.jobId.salary }}</div>
              <div class="col col-4" style="flex-basis: 25%;">{{ app.status }}</div>
            </li>
          {% endfor %}
    </div>
    <div class="d-flex justify-content-center m-2">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item border border-dark"><a class="page-link"
            href="{% url 'accounts:applications' %}?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="page-item border border-dark"><a class="page-link"
            href="{% url 'accounts:applications' %}?page={{ page_obj.next_page_number }}">next</a></li>
        {% endif %}
      </ul>
    </div>
  {% endif %}
</div>
{% endblock content %}

placement_portal/accounts/templates/accounts/applyMailTemplate.html
    <!DOCTYPE html>
<html>
 <head> 
  <meta charset="UTF-8"> 
  <meta content="width=device-width, initial-scale=1" name="viewport"> 
  <meta content="telephone=no" name="format-detection"> 
  <title>Apply Email</title> 
 </head> 
 <body style="width:100%;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0"> 
  <div class="es-wrapper-color" style="margin-top: 60px;"> 
   <table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top"> 
     <tr style="border-collapse:collapse"> 
      <td valign="top" style="padding:0;Margin:0"> 
       <table class="es-content" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%"> 
         <tr style="border-collapse:collapse"> 
          <td align="center" style="padding:0;Margin:0"> 
           <table class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center"> 
             <tr style="border-collapse:collapse"> 
              <td align="left" style="Margin:0;padding-top:20px;padding-bottom:20px;padding-left:40px;padding-right:40px"> 
               <table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> 
                 <tr style="border-collapse:collapse"> 
                  <td valign="top" align="center" style="padding:0;Margin:0;width:520px"> 
                   <table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> 
                     <tr style="border-collapse:collapse"> 
                      <td align="left" style="padding:0;Margin:0"><h1 style="Margin:0;line-height:36px;mso-line-height-rule:exactly;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;font-size:30px;font-style:normal;font-weight:normal;color:#4A7EB0">Job Application</h1></td> 
                     </tr> 
                     <tr style="border-collapse:collapse"> 
                      <td align="left" style="padding:0;Margin:0;padding-top:5px;padding-bottom:20px;font-size:0"> 
                       <table width="5%" height="100%" cellspacing="0" cellpadding="0" border="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> 
                         <tr style="border-collapse:collapse"> 
                          <td style="padding:0;Margin:0;border-bottom:2px solid #999999;background:#FFFFFF none repeat scroll 0% 0%;height:1px;width:100%;margin:0px"></td> 
                         </tr> 
                       </table></td> 
                     </tr> 
                     <tr style="border-collapse:collapse"> 
                      <td align="left" style="padding:0;Margin:0;padding-bottom:10px"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:21px;color:#666666"><span style="font-size:16px;line-height:24px">Hi, {{ first_name }},</span></p></td> 
                     </tr> 
                     <tr style="border-collapse:collapse"> 
                      <td align="left" style="padding:0;Margin:0"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:21px;color:#666666">Thanks for applying to {{ company_name }}! We've received your application for the position of {{ job_name }}.</b></p></td> 
                     </tr> 
                    <tr style="border-collapse:collapse"> 
                      <td align="left" style="padding:0;Margin:0"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:21px;color:#666666">Any updates to your application status will be reflected on your Application dashboard, so be sure to check back regularly.</p></td> 
                     </tr> 
                     <tr style="border-collapse:collapse"> 
                      <td align="left" style="padding:0;Margin:0"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:21px;color:#666666">Best regards,</td> 
                     </tr> 
                      <tr style="border-collapse:collapse"> 
                      <td align="left" style="padding:0;Margin:0"><p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:21px;color:#666666"><b>Placement Portal Team</b></td> 
                     </tr> 
                   </table></td> 
                 </tr> 
               </table></td> 
             </tr> 
           </table></td> 
         </tr> 
       </table> 
       </td> 
     </tr> 
   </table> 
  </div>  
 </body>
</html>

placement_portal/accounts/templates/accounts/dashboard.html
{% extends 'accounts/base.html' %}
{%block title%}Job alerts{%endblock title%}
{% block content %}
<div>
  <div class="container-fluid display-4 border-bottom">
    Job alerts
  </div>
  <div class="container-fluid row mx-auto">
    {% for job in page_obj %}
    <div class="col-sm-4 p-1">
      <div class="card border border-primary p-1">
        <div class="card-header">
          <h5>{{job.name}}</h5>
        </div>
        <div class="card-body">

          <div class="card-text"><span class="font-weight-bold">Company name: </span>{{job.cName.name}}</div>
          <div class="card-text"><span class="font-weight-bold">Salary: </span>{{job.salary}}</div>
          <div class="card-text"><span class="font-weight-bold">Address: </span>{{job.cName.address}}</div>
          <div class="card-text"><span class="font-weight-bold">About: </span>{{job.cName.about}}</div>
          <div class="card-text"><span class="font-weight-bold">Last date to apply:
            </span>{{job.lastDateToApply.day}}/{{job.lastDateToApply.month}}/{{job.lastDateToApply.year}}</div>
        </div>
        <div class="d-inline-flex flex-row-reverse ">
          <a class="btn btn-primary m-2" href="{{job.jdFile.url}}" role="button" target="blank">Details</a>
          <a class="btn btn-primary m-2" href="{% url 'accounts:apply' job.id %}" role="button">Apply</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  </span>
  <div class="d-flex justify-content-center m-2">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item border border-dark"><a class="page-link"
          href="{% url 'accounts:home' %}?page={{ page_obj.previous_page_number }}">previous</a></li>
      {% endif %}

      {% if page_obj.has_next %}
      <li class="page-item border border-dark"><a class="page-link"
          href="{% url 'accounts:home' %}?page={{ page_obj.next_page_number }}">next</a></li>
      {% endif %}
    </ul>
  </div>

</div>
{% endblock content %}

placement_portal/accounts/templates/accounts/footer.html
<div class="d-flex justify-content-center">
 <div>
     <a href = "{% url 'accounts:about'%}" style="font-size: 17px;">About</a>
 </div>
</div>

placement_portal/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block title %}Login{% endblock title%}
{% block content %}
<div class="mt-5 text-center">
	<div class="row">
		<div class="card border border-primary shadow p-4 col-4 mx-auto">
			<div>
				<h3>LOGIN</h3>
			</div>
			<div class="form_container">
				<form method="POST" action="">
					{% csrf_token %}
					<div class="input-group mb-3">
						<div class="input-group-append">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" name="username" placeholder="Registration ID" class="form-control">
					</div>

					<div class="input-group mb-3">
						<div class="input-group-append">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" name="password" placeholder="Password" class="form-control">
					</div>

					<div class=" mt-3 login_container">
						<input class="btn btn-block btn-primary" type="submit" value="Login">
					</div>
				</form>

			</div>
			<div class="mt-4">
				<div class=" links">
					Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

placement_portal/accounts/templates/accounts/messages.html
<div id="message-box" style="z-index: 999; position: absolute; top: 0; right: 0.5rem;">
{%if messages %}
	{% for message in messages %}
	<div class="alert alert-dismissible alert-primary">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<a href="#" class="alert-link">{{message}}</a>
	</div>
	{% endfor %}
{% endif %}
</div>

placement_portal/accounts/templates/accounts/navbar.html
<nav class="navbar">
  <div class="nav-name-container">Hello,
    {% if not request.user.is_superuser %}
      <a class="nav-name" href="{% url 'accounts:home'%}">{{request.user.first_name}}&nbsp;{{request.user.last_name}}</a>
    {% else %}
      <a class="nav-name" href="{% url 'accounts:home'%}">Admin</a>
    {% endif %}
  </div>
  <div>
    
    <ul class="">
      {% if not request.user.is_superuser %}
        <li class="nav-item">
          <a class="" href="{% url 'accounts:notices' %}">Notices</a>
        </li>
        <li class="nav-item">
          <a class="" href="{% url 'accounts:applications' %}">My applications</a>
        </li>
      {% endif %}
        <li class="nav-item">
          <a class="" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
    </ul>
  </div>
</nav>

placement_portal/accounts/templates/accounts/notices.html
{% extends 'accounts/base.html' %}
{% block title %}Notices{% endblock title%}
{% block content %}
<div>
  <div class="display-4 border-bottom mx-1">
    Notices
  </div>
  <div class="card-columns mx-auto">
    {% for n in page_obj %}
    <div class="">
      <div class="card border border-primary p-1">
        <div class="card-header">
          <h5>{{n.name}}</h5>
        </div>
        <div class="card-body">

          <div class="card-text"><span class="font-weight-bold">Subject: </span>{{n.subject}}</div>
          <div class="card-text"><span class="font-weight-bold">Date: </span>{{n.date}}</div>
        </div>
        <div class="d-inline-flex flex-row-reverse ">
          <a class="btn btn-primary m-2" href="{{n.noticeFile.url}}" role="button" target="_blank">Details</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="d-flex justify-content-center m-2">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item border border-dark"><a class="page-link"
          href="{% url 'accounts:notices' %}?page={{ page_obj.previous_page_number }}">previous</a></li>
      {% endif %}

      {% if page_obj.has_next %}
      <li class="page-item border border-dark"><a class="page-link"
          href="{% url 'accounts:notices' %}?page={{ page_obj.next_page_number }}">next</a></li>
      {% endif %}
    </ul>
  </div>
</div>
{% endblock content %}

placement_portal/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% block title %}Register{% endblock title%}
{% block content %}
<div class="text-center mt-5">
	<div class="h-100">
		
		<div class="row">
			<div class="card border border-primary shadow p-4 col-4 mx-auto">
				<div>
					{% for errorlist in registerForm.errors.values %}
					{% for error in errorlist %}
					<div class="alert alert-dismissible alert-danger">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<strong>{{error}}</strong>
					</div>
					{% endfor %}
					{% endfor %}
				</div>
				<div class="">
					<h3 id="form-title">REGISTER</h3>
				</div>
				<div class="form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{registerForm.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-id-card"></i></span>
							</div>
							{{registerForm.first_name}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-id-card"></i></span>
							</div>
							{{registerForm.last_name}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope"></i></span>
							</div>
							{{registerForm.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{registerForm.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{registerForm.password2}}
						</div>
						<div class="d-flex justify-content-center mt-3 login_container">
							<input class="btn btn-block btn-primary" type="submit" value="Register Account">
						</div>

					</form>
				</div>
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>

	var form_fields = document.getElementsByTagName('input')
	form_fields[1].placeholder = 'Registration ID';
	form_fields[2].placeholder = 'First name';
	form_fields[3].placeholder = 'Last name';
	form_fields[4].placeholder = 'Email';
	form_fields[5].placeholder = 'Enter password...';
	form_fields[6].placeholder = 'Re-enter Password...';

	for (var field in form_fields) {
		form_fields[field].className += ' form-control'
	}
</script>

{% endblock content %}